export enum ActionType {
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  LOGOUT = "LOGOUT",
  VERIFY_REQUEST = "VERIFY_REQUEST",
  VERIFY_SUCCESS = "VERIFY_SUCCESS",
  VERIFY_FAIL = "VERIFY_FAIL",
}
